package com.architect.atlas.navigationEngine.tasks.routingEngine.apple

import com.architect.atlas.navigationEngine.tasks.models.Quad
import com.architect.atlas.navigationEngine.tasks.models.ScreenMetadata
import com.architect.atlas.navigationEngine.tasks.routingEngine.apple.helpers.scanViewModelSwiftAnnotations
import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputFile
import org.gradle.api.tasks.Optional
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction
import java.io.File

@CacheableTask
abstract class AppleWatchNavigationEngineGeneratorTask : DefaultTask() {
    @get:OutputDirectory
    abstract val outputAppleWatchDir: DirectoryProperty

    @get:Input
    abstract var appleWatchOutputFiles: List<File>

    @get:Input
    abstract var projectCoreName: String

    @get:Optional
    @get:InputFile
    @get:PathSensitive(PathSensitivity.NONE)
    abstract val inputHashFile: RegularFileProperty

    init {
        group = "AtlasNavigation"
        description =
            "Generates the platform-specific navigation engine implementations (AppleWatch ONLY)"

        outputs.upToDateWhen {
            val file = inputHashFile.orNull?.asFile
            file != null && file.exists()
        }
    }

    @TaskAction
    fun generateNavigatorClass() {
        generateWatchOSNavigation(scanViewModelSwiftAnnotations(appleWatchOutputFiles).map {
            ScreenMetadata(
                it.first,
                it.second,
                it.fourth
            )
        })
    }

    private fun generateWatchOSNavigation(screens: List<ScreenMetadata>) {
        val initial = screens.firstOrNull { it.isInitial } ?: screens.firstOrNull()
        val initialViewModel = initial?.viewModel ?: "/* MissingInitialVM */"
        initial?.screen?.replace(":", "") ?: "/*MissingInitialScreen */"

        val watchImpl = buildString {
            appendLine("import SwiftUI")
            appendLine("import $projectCoreName")
            appendLine()
            appendLine("struct RouteToken: Hashable, Identifiable {")
            appendLine("    let id = UUID()")
            appendLine("    let viewModelType: String")
            appendLine("}")
            appendLine()
            appendLine("struct LifecycleAwareWatchView<Content: View>: View {")
            appendLine("    let content: () -> Content")
            appendLine("    let onAppear: () -> Void")
            appendLine("    let onDisappear: () -> Void")
            appendLine("    init(_ content: @escaping () -> Content, onAppear: @escaping () -> Void, onDisappear: @escaping () -> Void) {")
            appendLine("        self.content = content")
            appendLine("        self.onAppear = onAppear")
            appendLine("        self.onDisappear = onDisappear")
            appendLine("    }")
            appendLine("    var body: some View {")
            appendLine("        content()")
            appendLine("            .onAppear { onAppear() }")
            appendLine("            .onDisappear { onDisappear() }")
            appendLine("    }")
            appendLine("}")
            appendLine()
            appendLine("final class WatchNavigationEngine: ObservableObject {")
            appendLine("    public static let shared = WatchNavigationEngine()")
            appendLine("    @Published public var path = NavigationPath()")
            appendLine("    @Published public var presented: RouteToken? = nil")
            appendLine("    var stack: [ViewModel] = []")
            appendLine("    private var vmStore: [UUID: ViewModel] = [:]")
            appendLine("    private var bootstrapped: Set<UUID> = []")
            appendLine("    private init() {}")
            appendLine()
            appendLine("    public func routeWithParams(viewModelType: String, params: Any? = nil, isModal: Bool = false) {")
            appendLine("        let (token, vm) = buildVMAndToken(viewModelType: viewModelType, params: params)")
            appendLine("        if isModal {")
            appendLine("            presented = token")
            appendLine("        } else {")
            appendLine("            path.append(token)")
            appendLine("        }")
            appendLine("        stack.append(vm)")
            appendLine("    }")
            appendLine()
            appendLine("    @MainActor")
            appendLine("    func setNavigationStack(stack: [String], params: Any?) {")
            appendLine("        presented = nil")
            appendLine("        for (_, vm) in vmStore {")
            appendLine("            Task { @MainActor in")
            appendLine("                vm.onDestroy()")
            appendLine("                vm.onCleared()")
            appendLine("            }")
            appendLine("        }")
            appendLine("        vmStore.removeAll()")
            appendLine("        bootstrapped.removeAll()")
            appendLine("        self.stack.removeAll()")
            appendLine("        self.path = NavigationPath()")
            appendLine("        guard let first = stack.first else { return }")
            appendLine("        let (rootToken, rootVM) = buildVMAndToken(viewModelType: first, params: params)")
            appendLine("        _unsafeStoreRootVM(rootVM, token: rootToken)")
            appendLine("        self.stack = [rootVM]")
            appendLine("        rootVM.bootstrapVmFromNavEngine()")
            appendLine("        bootstrapped.insert(rootToken.id)")
            appendLine("        if stack.count > 1 {")
            appendLine("            for name in stack.dropFirst() {")
            appendLine("                let (t, vm) = buildVMAndToken(viewModelType: name, params: params)")
            appendLine("                self.path.append(t)")
            appendLine("                self.stack.append(vm)")
            appendLine("            }")
            appendLine("        }")
            appendLine("    }")
            appendLine()
            appendLine("    @MainActor")
            appendLine("    func replaceStack(with viewModelType: String, params: Any?) {")
            appendLine("        setNavigationStack(stack: [viewModelType], params: params)")
            appendLine("    }")
            appendLine()
            appendLine("    @MainActor")
            appendLine("    func replaceCurrentScreen(with viewModelType: String, params: Any?) {")
            appendLine("        guard !stack.isEmpty else {")
            appendLine("            routeWithParams(viewModelType: viewModelType, params: params)")
            appendLine("            return")
            appendLine("        }")
            appendLine("        if presented != nil {")
            appendLine("            presented = nil")
            appendLine("        }")
            appendLine("        if path.isEmpty {")
            appendLine("            replaceStack(with: viewModelType, params: params)")
            appendLine("            return")
            appendLine("        }")
            appendLine("        let currentWas = stack.removeLast()")
            appendLine("        Task { @MainActor in")
            appendLine("            currentWas.onDestroy()")
            appendLine("            currentWas.onCleared()")
            appendLine("        }")
            appendLine("        if !path.isEmpty {")
            appendLine("            if let last = path.last as? RouteToken { bootstrapped.remove(last.id) }")
            appendLine("            path.removeLast()")
            appendLine("        }")
            appendLine("        let (replacementToken, replacementVM) = buildVMAndToken(viewModelType: viewModelType, params: params)")
            appendLine("        path.append(replacementToken)")
            appendLine("        stack.append(replacementVM)")
            appendLine("    }")
            appendLine()
            appendLine("    func getNavigationStack() -> [String] { return stack.map { String(describing: type(of: $0)) } }")
            appendLine()
            appendLine("    func popToRoot(animate: Bool = true, params: Any? = nil) {")
            appendLine("        if let prev = stack.first as? Poppable, let p = params { prev.onPopParams(params: p) }")
            appendLine("        if stack.count > 1 {")
            appendLine("            let removing = stack.dropFirst()")
            appendLine("            for vm in removing {")
            appendLine("                Task { @MainActor in")
            appendLine("                    vm.onDestroy()")
            appendLine("                    vm.onCleared()")
            appendLine("                }")
            appendLine("            }")
            appendLine("            stack.removeSubrange(1..<stack.count)")
            appendLine("        }")
            appendLine("        withAnimation(animate ? .default : nil) {")
            appendLine("            if !path.isEmpty {")
            appendLine("                if let last = path.last as? RouteToken { bootstrapped.remove(last.id) }")
            appendLine("                path.removeLast(path.count)")
            appendLine("            }")
            appendLine("        }")
            appendLine("    }")
            appendLine()
            appendLine("    func popPage(animate: Bool = true, params: Any? = nil) {")
            appendLine("        if stack.count >= 2, let prev = stack[stack.count - 2] as? Poppable, let p = params { prev.onPopParams(params: p) }")
            appendLine("        if let removed = stack.popLast() {")
            appendLine("            Task { @MainActor in")
            appendLine("                removed.onDestroy()")
            appendLine("                removed.onCleared()")
            appendLine("            }")
            appendLine("        }")
            appendLine("        withAnimation(animate ? .default : nil) {")
            appendLine("            if !path.isEmpty {")
            appendLine("                if let last = path.last as? RouteToken { bootstrapped.remove(last.id) }")
            appendLine("                path.removeLast()")
            appendLine("            }")
            appendLine("        }")
            appendLine("    }")
            appendLine()
            appendLine("    func popPagesWithCount(count: Int, animate: Bool = true, params: Any? = nil) {")
            appendLine("        let pops = min(count, path.count)")
            appendLine("        if stack.count > pops, let prev = stack[stack.count - pops - 1] as? Poppable, let p = params { prev.onPopParams(params: p) }")
            appendLine("        if pops > 0 {")
            appendLine("            for _ in 0..<pops {")
            appendLine("                if let removed = stack.popLast() {")
            appendLine("                    Task { @MainActor in")
            appendLine("                        removed.onDestroy()")
            appendLine("                        removed.onCleared()")
            appendLine("                    }")
            appendLine("                }")
            appendLine("            }")
            appendLine("        }")
            appendLine("        withAnimation(animate ? .default : nil) {")
            appendLine("            for _ in 0..<pops {")
            appendLine("                if !path.isEmpty {")
            appendLine("                    if let last = path.last as? RouteToken { bootstrapped.remove(last.id) }")
            appendLine("                    path.removeLast()")
            appendLine("                }")
            appendLine("            }")
            appendLine("        }")
            appendLine("    }")
            appendLine()
            appendLine("    @MainActor")
            appendLine("    func popToPage(route: String, params: Any?) {")
            appendLine("        if presented != nil {")
            appendLine("            presented = nil")
            appendLine("        }")
            appendLine("        guard !stack.isEmpty else { return }")
            appendLine("        let targetIndexOpt = stack.enumerated().first(where: { (_, vm) in")
            appendLine("            String(describing: type(of: vm)) == route")
            appendLine("        })?.offset")
            appendLine("        guard let targetIndex = targetIndexOpt else { return }")
            appendLine("        val popsCount = (stack.count - 1) - targetIndex")
            appendLine("        if popsCount < 0 { return }")
            appendLine("        if let p = params, let target = stack[targetIndex] as? Poppable {")
            appendLine("            target.onPopParams(params: p)")
            appendLine("        }")
            appendLine("        if popsCount > 0 {")
            appendLine("            for vm in stack.suffix(popsCount) {")
            appendLine("                Task { @MainActor in")
            appendLine("                    vm.onDestroy()")
            appendLine("                    vm.onCleared()")
            appendLine("                }")
            appendLine("            }")
            appendLine("            stack.removeLast(popsCount)")
            appendLine("        }")
            appendLine("        if popsCount > 0 {")
            appendLine("            withAnimation(.default) {")
            appendLine("                for _ in 0..<popsCount {")
            appendLine("                    if !path.isEmpty {")
            appendLine("                        if let last = path.last as? RouteToken { bootstrapped.remove(last.id) }")
            appendLine("                        path.removeLast()")
            appendLine("                    }")
            appendLine("                }")
            appendLine("            }")
            appendLine("        }")
            appendLine("    }")
            appendLine()
            appendLine("    func dismissModal(animate: Bool = true, params: Any? = nil) {")
            appendLine("        if presented != nil, let prev = stack.last as? Poppable, let p = params { prev.onPopParams(params: p) }")
            appendLine("        withAnimation(animate ? .default : nil) { presented = nil }")
            appendLine("    }")
            appendLine()
            appendLine("    private func buildVMAndToken(viewModelType: String, params: Any?) -> (RouteToken, ViewModel) {")
            appendLine("        func resolve<T: ViewModel>(_ type: T.Type) -> T {")
            appendLine("            let clazz = SwiftClassGenerator.companion.getClazz(type: type)")
            appendLine("            return AtlasDI.companion.resolveServiceNullableByName(clazz: clazz) as! T")
            appendLine("        }")
            appendLine("        let vm: ViewModel = {")
            appendLine("            switch viewModelType {")
            for ((vm, _, _) in screens) {
                val vmSimple = vm.substringAfterLast(".")
                appendLine("            case \"$vmSimple\":")
                appendLine("                let v = resolve($vmSimple.self)")
                appendLine("                if let p = params { v.tryHandlePush(params: p) }")
                appendLine("                return v")
            }
            appendLine("            default:")
            appendLine("                let v = resolve(UnifiedErrorScreenViewModel.self)")
            appendLine("                return v")
            appendLine("            }")
            appendLine("        }()")
            appendLine("        let token = RouteToken(viewModelType: viewModelType)")
            appendLine("        vmStore[token.id] = vm")
            appendLine("        return (token, vm)")
            appendLine("    }")
            appendLine()
            appendLine("    func viewFor(token: RouteToken) -> AnyView {")
            appendLine("        guard let vm = vmStore[token.id] else { return AnyView(Text(\"Missing VM\")) }")
            appendLine("        switch token.viewModelType {")
            for ((vm, screen, _) in screens) {
                val vmSimple = vm.substringAfterLast(".")
                val screenName = screen.replace(":", "")
                appendLine("        case \"$vmSimple\":")
                appendLine("            let typed = vm as! $vmSimple")
                appendLine("            return AnyView(LifecycleAwareWatchView({ $screenName(vm: typed) }, onAppear: {")
                appendLine("                if !bootstrapped.contains(token.id) {")
                appendLine("                    typed.bootstrapVmFromNavEngine()")
                appendLine("                    bootstrapped.insert(token.id)")
                appendLine("                }")
                appendLine("                typed.onAppearing()")
                appendLine("            }, onDisappear: {")
                appendLine("                typed.onDisappearing()")
                appendLine("            }))")
            }
            appendLine("        default:")
            appendLine("            return AnyView(Text(\"\"))")
            appendLine("        }")
            appendLine("    }")
            appendLine()
            appendLine("    func onRouteDisappeared(_ token: RouteToken) {")
            appendLine("        if let vm = vmStore[token.id] {")
            appendLine("            Task { @MainActor in")
            appendLine("                vm.onDestroy()")
            appendLine("                vm.onCleared()")
            appendLine("            }")
            appendLine("        }")
            appendLine("        vmStore[token.id] = nil")
            appendLine("        bootstrapped.remove(token.id)")
            appendLine("    }")
            appendLine()
            appendLine("    fileprivate func _unsafeStoreRootVM(_ vm: ViewModel, token: RouteToken) {")
            appendLine("        self.path = NavigationPath()")
            appendLine("        self.presented = nil")
            appendLine("        self.vmStore[token.id] = vm")
            appendLine("    }")
            appendLine("}")
            appendLine()
            appendLine("struct WatchNavRootView: View {")
            appendLine("    @StateObject private var router = WatchNavigationEngine.shared")
            appendLine("    @State private var rootToken: RouteToken? = nil")
            appendLine("    var body: some View {")
            appendLine("        NavigationStack(path: ${'$'}router.path) {")
            appendLine("            Group {")
            appendLine("                if let t = rootToken {")
            appendLine("                    router.viewFor(token: t)")
            appendLine("                } else {")
            appendLine("                    ProgressView().task {")
            appendLine("                        await buildRoot()")
            appendLine("                    }")
            appendLine("                }")
            appendLine("            }")
            appendLine("            .navigationDestination(for: RouteToken.self) { token in")
            appendLine("                router.viewFor(token: token)")
            appendLine("                    .onDisappear { router.onRouteDisappeared(token) }")
            appendLine("            }")
            appendLine("            .sheet(item: ${'$'}router.presented) { token in")
            appendLine("                router.viewFor(token: token)")
            appendLine("                    .onDisappear { router.onRouteDisappeared(token) }")
            appendLine("            }")
            appendLine("        }")
            appendLine("    }")
            appendLine()
            appendLine("    @MainActor")
            appendLine("    private func buildRoot() async {")
            appendLine("        let clazz = SwiftClassGenerator.companion.getClazz(type: $initialViewModel.self)")
            appendLine("        let vm = AtlasDI.companion.resolveServiceNullableByName(clazz: clazz) as! $initialViewModel")
            appendLine("        let token = RouteToken(viewModelType: \"$initialViewModel\")")
            appendLine("        WatchNavigationEngine.shared.stack = [vm]")
            appendLine("        WatchNavigationEngine.shared._unsafeStoreRootVM(vm, token: token)")
            appendLine("        vm.bootstrapVmFromNavEngine()")
            appendLine("        WatchNavigationEngine.shared.bootstrapped.insert(token.id)")
            appendLine("        rootToken = token")
            appendLine("    }")
            appendLine("}")
            appendLine()
            appendLine("class WatchAtlasNavigationService: NSObject, @preconcurrency AtlasNavigationService {")
            appendLine("    static let shared = WatchAtlasNavigationService()")
            appendLine("    func setNavigationStack(stack: [ViewModel], params: Any?) {")
            appendLine("        DispatchQueue.main.async {")
            appendLine("            let names = stack.map { String(describing: type(of: $0)) }")
            appendLine("            WatchNavigationEngine.shared.setNavigationStack(stack: names, params: params)")
            appendLine("        }")
            appendLine("    }")
            appendLine("    func getNavigationStack() -> [ViewModel] {")
            appendLine("        return WatchNavigationEngine.shared.stack")
            appendLine("    }")
            appendLine("    func navigateToPage(viewModelClass: KotlinKClass, params: Any?) {")
            appendLine("        DispatchQueue.main.async {")
            appendLine("            WatchNavigationEngine.shared.routeWithParams(viewModelType: viewModelClass.simpleName!, params: params)")
            appendLine("        }")
            appendLine("    }")
            appendLine("    func navigateToPagePushAndReplace(viewModelClass: KotlinKClass, params: Any?) {")
            appendLine("        DispatchQueue.main.async {")
            appendLine("            WatchNavigationEngine.shared.replaceStack(with: viewModelClass.simpleName!, params: params)")
            appendLine("        }")
            appendLine("    }")
            appendLine("    func navigateToPagePushAndReplaceCurrentScreen(viewModelClass: KotlinKClass, params: Any?) {")
            appendLine("        DispatchQueue.main.async {")
            appendLine("            WatchNavigationEngine.shared.replaceCurrentScreen(with: viewModelClass.simpleName!, params: params)")
            appendLine("        }")
            appendLine("    }")
            appendLine("    func navigateToPageModal(viewModelClass: KotlinKClass, params: Any?) {")
            appendLine("        DispatchQueue.main.async {")
            appendLine("            WatchNavigationEngine.shared.routeWithParams(viewModelType: viewModelClass.simpleName!, params: params, isModal: true)")
            appendLine("        }")
            appendLine("    }")
            appendLine("    func popToRoot(animate: Bool = true, params: Any? = nil) {")
            appendLine("        DispatchQueue.main.async {")
            appendLine("            WatchNavigationEngine.shared.popToRoot(animate: animate, params: params)")
            appendLine("        }")
            appendLine("    }")
            appendLine("    func popPage(animate: Bool = true, params: Any? = nil) {")
            appendLine("        DispatchQueue.main.async {")
            appendLine("            WatchNavigationEngine.shared.popPage(animate: animate, params: params)")
            appendLine("        }")
            appendLine("    }")
            appendLine("    func popPagesWithCount(countOfPages: Int32, animate: Bool, params: Any?) {")
            appendLine("        DispatchQueue.main.async {")
            appendLine("            WatchNavigationEngine.shared.popPagesWithCount(count: Int(countOfPages), animate: animate, params: params)")
            appendLine("        }")
            appendLine("    }")
            appendLine("    func popToPage(route: String, params: Any? = nil) {")
            appendLine("        DispatchQueue.main.async {")
            appendLine("            WatchNavigationEngine.shared.popToPage(route: route, params: params)")
            appendLine("        }")
            appendLine("    }")
            appendLine("    func dismissModal(animate: Bool = true, params: Any? = nil) {")
            appendLine("        DispatchQueue.main.async {")
            appendLine("            WatchNavigationEngine.shared.dismissModal(animate: animate, params: params)")
            appendLine("        }")
            appendLine("    }")
            appendLine("}")
        }

        val iosOut = outputAppleWatchDir.get().asFile
        iosOut.mkdirs()
        File(iosOut, "WatchNavigationEngine.swift").writeText(watchImpl)
    }


}